steps:
  - name: gcr.io/cloud-builders/git
    args: [ 'fetch', '--unshallow' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/cirrus-ci-community/terminal:$TAG_NAME', '-t', 'gcr.io/cirrus-ci-community/terminal:latest', '.' ]
timeout: 2400s
images: [ 'gcr.io/cirrus-ci-community/terminal:$TAG_NAME', 'gcr.io/cirrus-ci-community/terminal:latest' ]
