// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: terminal.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GuestTerminalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Operation:
	//
	//	*GuestTerminalRequest_Hello_
	//	*GuestTerminalRequest_ChangeDimensions
	//	*GuestTerminalRequest_Input
	Operation isGuestTerminalRequest_Operation `protobuf_oneof:"operation"`
}

func (x *GuestTerminalRequest) Reset() {
	*x = GuestTerminalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_terminal_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuestTerminalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuestTerminalRequest) ProtoMessage() {}

func (x *GuestTerminalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_terminal_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuestTerminalRequest.ProtoReflect.Descriptor instead.
func (*GuestTerminalRequest) Descriptor() ([]byte, []int) {
	return file_terminal_proto_rawDescGZIP(), []int{0}
}

func (m *GuestTerminalRequest) GetOperation() isGuestTerminalRequest_Operation {
	if m != nil {
		return m.Operation
	}
	return nil
}

func (x *GuestTerminalRequest) GetHello() *GuestTerminalRequest_Hello {
	if x, ok := x.GetOperation().(*GuestTerminalRequest_Hello_); ok {
		return x.Hello
	}
	return nil
}

func (x *GuestTerminalRequest) GetChangeDimensions() *TerminalDimensions {
	if x, ok := x.GetOperation().(*GuestTerminalRequest_ChangeDimensions); ok {
		return x.ChangeDimensions
	}
	return nil
}

func (x *GuestTerminalRequest) GetInput() *Data {
	if x, ok := x.GetOperation().(*GuestTerminalRequest_Input); ok {
		return x.Input
	}
	return nil
}

type isGuestTerminalRequest_Operation interface {
	isGuestTerminalRequest_Operation()
}

type GuestTerminalRequest_Hello_ struct {
	// Mandatory first message from a Guest after it opens this channel
	Hello *GuestTerminalRequest_Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type GuestTerminalRequest_ChangeDimensions struct {
	// Used to synchronize terminal dimensions on the Host after e.g. web UI terminal size changes
	ChangeDimensions *TerminalDimensions `protobuf:"bytes,2,opt,name=change_dimensions,json=changeDimensions,proto3,oneof"`
}

type GuestTerminalRequest_Input struct {
	// Terminal input to the Host
	Input *Data `protobuf:"bytes,3,opt,name=input,proto3,oneof"`
}

func (*GuestTerminalRequest_Hello_) isGuestTerminalRequest_Operation() {}

func (*GuestTerminalRequest_ChangeDimensions) isGuestTerminalRequest_Operation() {}

func (*GuestTerminalRequest_Input) isGuestTerminalRequest_Operation() {}

type GuestTerminalResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Operation:
	//
	//	*GuestTerminalResponse_Output
	Operation isGuestTerminalResponse_Operation `protobuf_oneof:"operation"`
}

func (x *GuestTerminalResponse) Reset() {
	*x = GuestTerminalResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_terminal_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuestTerminalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuestTerminalResponse) ProtoMessage() {}

func (x *GuestTerminalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_terminal_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuestTerminalResponse.ProtoReflect.Descriptor instead.
func (*GuestTerminalResponse) Descriptor() ([]byte, []int) {
	return file_terminal_proto_rawDescGZIP(), []int{1}
}

func (m *GuestTerminalResponse) GetOperation() isGuestTerminalResponse_Operation {
	if m != nil {
		return m.Operation
	}
	return nil
}

func (x *GuestTerminalResponse) GetOutput() *Data {
	if x, ok := x.GetOperation().(*GuestTerminalResponse_Output); ok {
		return x.Output
	}
	return nil
}

type isGuestTerminalResponse_Operation interface {
	isGuestTerminalResponse_Operation()
}

type GuestTerminalResponse_Output struct {
	// Terminal output from the Host
	Output *Data `protobuf:"bytes,1,opt,name=output,proto3,oneof"`
}

func (*GuestTerminalResponse_Output) isGuestTerminalResponse_Operation() {}

type HostControlRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Operation:
	//
	//	*HostControlRequest_Hello_
	Operation isHostControlRequest_Operation `protobuf_oneof:"operation"`
}

func (x *HostControlRequest) Reset() {
	*x = HostControlRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_terminal_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostControlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostControlRequest) ProtoMessage() {}

func (x *HostControlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_terminal_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostControlRequest.ProtoReflect.Descriptor instead.
func (*HostControlRequest) Descriptor() ([]byte, []int) {
	return file_terminal_proto_rawDescGZIP(), []int{2}
}

func (m *HostControlRequest) GetOperation() isHostControlRequest_Operation {
	if m != nil {
		return m.Operation
	}
	return nil
}

func (x *HostControlRequest) GetHello() *HostControlRequest_Hello {
	if x, ok := x.GetOperation().(*HostControlRequest_Hello_); ok {
		return x.Hello
	}
	return nil
}

type isHostControlRequest_Operation interface {
	isHostControlRequest_Operation()
}

type HostControlRequest_Hello_ struct {
	// Mandatory first message from the Host after it opens this channel
	Hello *HostControlRequest_Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

func (*HostControlRequest_Hello_) isHostControlRequest_Operation() {}

type HostControlResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Operation:
	//
	//	*HostControlResponse_Hello_
	//	*HostControlResponse_DataChannelRequest_
	Operation isHostControlResponse_Operation `protobuf_oneof:"operation"`
}

func (x *HostControlResponse) Reset() {
	*x = HostControlResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_terminal_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostControlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostControlResponse) ProtoMessage() {}

func (x *HostControlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_terminal_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostControlResponse.ProtoReflect.Descriptor instead.
func (*HostControlResponse) Descriptor() ([]byte, []int) {
	return file_terminal_proto_rawDescGZIP(), []int{3}
}

func (m *HostControlResponse) GetOperation() isHostControlResponse_Operation {
	if m != nil {
		return m.Operation
	}
	return nil
}

func (x *HostControlResponse) GetHello() *HostControlResponse_Hello {
	if x, ok := x.GetOperation().(*HostControlResponse_Hello_); ok {
		return x.Hello
	}
	return nil
}

func (x *HostControlResponse) GetDataChannelRequest() *HostControlResponse_DataChannelRequest {
	if x, ok := x.GetOperation().(*HostControlResponse_DataChannelRequest_); ok {
		return x.DataChannelRequest
	}
	return nil
}

type isHostControlResponse_Operation interface {
	isHostControlResponse_Operation()
}

type HostControlResponse_Hello_ struct {
	// Mandatory reply to the Hello message sent from the Host
	Hello *HostControlResponse_Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type HostControlResponse_DataChannelRequest_ struct {
	// Emitted when a Guest opens a new terminal channel
	DataChannelRequest *HostControlResponse_DataChannelRequest `protobuf:"bytes,2,opt,name=data_channel_request,json=dataChannelRequest,proto3,oneof"`
}

func (*HostControlResponse_Hello_) isHostControlResponse_Operation() {}

func (*HostControlResponse_DataChannelRequest_) isHostControlResponse_Operation() {}

type HostDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Operation:
	//
	//	*HostDataRequest_Hello_
	//	*HostDataRequest_Output
	Operation isHostDataRequest_Operation `protobuf_oneof:"operation"`
}

func (x *HostDataRequest) Reset() {
	*x = HostDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_terminal_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostDataRequest) ProtoMessage() {}

func (x *HostDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_terminal_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostDataRequest.ProtoReflect.Descriptor instead.
func (*HostDataRequest) Descriptor() ([]byte, []int) {
	return file_terminal_proto_rawDescGZIP(), []int{4}
}

func (m *HostDataRequest) GetOperation() isHostDataRequest_Operation {
	if m != nil {
		return m.Operation
	}
	return nil
}

func (x *HostDataRequest) GetHello() *HostDataRequest_Hello {
	if x, ok := x.GetOperation().(*HostDataRequest_Hello_); ok {
		return x.Hello
	}
	return nil
}

func (x *HostDataRequest) GetOutput() *Data {
	if x, ok := x.GetOperation().(*HostDataRequest_Output); ok {
		return x.Output
	}
	return nil
}

type isHostDataRequest_Operation interface {
	isHostDataRequest_Operation()
}

type HostDataRequest_Hello_ struct {
	// Mandatory first message to be sent by the Host
	Hello *HostDataRequest_Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type HostDataRequest_Output struct {
	// Terminal output to the Guest
	Output *Data `protobuf:"bytes,2,opt,name=output,proto3,oneof"`
}

func (*HostDataRequest_Hello_) isHostDataRequest_Operation() {}

func (*HostDataRequest_Output) isHostDataRequest_Operation() {}

type HostDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Operation:
	//
	//	*HostDataResponse_ChangeDimensions
	//	*HostDataResponse_Input
	Operation isHostDataResponse_Operation `protobuf_oneof:"operation"`
}

func (x *HostDataResponse) Reset() {
	*x = HostDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_terminal_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostDataResponse) ProtoMessage() {}

func (x *HostDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_terminal_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostDataResponse.ProtoReflect.Descriptor instead.
func (*HostDataResponse) Descriptor() ([]byte, []int) {
	return file_terminal_proto_rawDescGZIP(), []int{5}
}

func (m *HostDataResponse) GetOperation() isHostDataResponse_Operation {
	if m != nil {
		return m.Operation
	}
	return nil
}

func (x *HostDataResponse) GetChangeDimensions() *TerminalDimensions {
	if x, ok := x.GetOperation().(*HostDataResponse_ChangeDimensions); ok {
		return x.ChangeDimensions
	}
	return nil
}

func (x *HostDataResponse) GetInput() *Data {
	if x, ok := x.GetOperation().(*HostDataResponse_Input); ok {
		return x.Input
	}
	return nil
}

type isHostDataResponse_Operation interface {
	isHostDataResponse_Operation()
}

type HostDataResponse_ChangeDimensions struct {
	// Emitted when the Guest decides to change an already created terminal dimensions (e.g. when the web UI terminal size changes)
	ChangeDimensions *TerminalDimensions `protobuf:"bytes,1,opt,name=change_dimensions,json=changeDimensions,proto3,oneof"`
}

type HostDataResponse_Input struct {
	// Terminal input from the Guest
	Input *Data `protobuf:"bytes,2,opt,name=input,proto3,oneof"`
}

func (*HostDataResponse_ChangeDimensions) isHostDataResponse_Operation() {}

func (*HostDataResponse_Input) isHostDataResponse_Operation() {}

type TerminalDimensions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WidthColumns uint32 `protobuf:"varint,1,opt,name=width_columns,json=widthColumns,proto3" json:"width_columns,omitempty"`
	HeightRows   uint32 `protobuf:"varint,2,opt,name=height_rows,json=heightRows,proto3" json:"height_rows,omitempty"`
}

func (x *TerminalDimensions) Reset() {
	*x = TerminalDimensions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_terminal_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TerminalDimensions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalDimensions) ProtoMessage() {}

func (x *TerminalDimensions) ProtoReflect() protoreflect.Message {
	mi := &file_terminal_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalDimensions.ProtoReflect.Descriptor instead.
func (*TerminalDimensions) Descriptor() ([]byte, []int) {
	return file_terminal_proto_rawDescGZIP(), []int{6}
}

func (x *TerminalDimensions) GetWidthColumns() uint32 {
	if x != nil {
		return x.WidthColumns
	}
	return 0
}

func (x *TerminalDimensions) GetHeightRows() uint32 {
	if x != nil {
		return x.HeightRows
	}
	return 0
}

type Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Data) Reset() {
	*x = Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_terminal_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_terminal_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_terminal_proto_rawDescGZIP(), []int{7}
}

func (x *Data) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Error) Reset() {
	*x = Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_terminal_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_terminal_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_terminal_proto_rawDescGZIP(), []int{8}
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GuestTerminalRequest_Hello struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Unique Host identifier assigned by the HostService
	Locator string `protobuf:"bytes,1,opt,name=locator,proto3" json:"locator,omitempty"`
	// Symmetric key used to authenticate against a Host specified by the locator above,
	// should match the Host's trusted_secret
	Secret string `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	// Dimensions of the terminal to be created on the Host
	RequestedDimensions *TerminalDimensions `protobuf:"bytes,3,opt,name=requested_dimensions,json=requestedDimensions,proto3" json:"requested_dimensions,omitempty"`
}

func (x *GuestTerminalRequest_Hello) Reset() {
	*x = GuestTerminalRequest_Hello{}
	if protoimpl.UnsafeEnabled {
		mi := &file_terminal_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuestTerminalRequest_Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuestTerminalRequest_Hello) ProtoMessage() {}

func (x *GuestTerminalRequest_Hello) ProtoReflect() protoreflect.Message {
	mi := &file_terminal_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuestTerminalRequest_Hello.ProtoReflect.Descriptor instead.
func (*GuestTerminalRequest_Hello) Descriptor() ([]byte, []int) {
	return file_terminal_proto_rawDescGZIP(), []int{0, 0}
}

func (x *GuestTerminalRequest_Hello) GetLocator() string {
	if x != nil {
		return x.Locator
	}
	return ""
}

func (x *GuestTerminalRequest_Hello) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *GuestTerminalRequest_Hello) GetRequestedDimensions() *TerminalDimensions {
	if x != nil {
		return x.RequestedDimensions
	}
	return nil
}

type HostControlRequest_Hello struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Symmetric key, the knowledge of which by the Guest can be used to spawn a new terminal on to this Host
	TrustedSecret string `protobuf:"bytes,1,opt,name=trusted_secret,json=trustedSecret,proto3" json:"trusted_secret,omitempty"`
}

func (x *HostControlRequest_Hello) Reset() {
	*x = HostControlRequest_Hello{}
	if protoimpl.UnsafeEnabled {
		mi := &file_terminal_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostControlRequest_Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostControlRequest_Hello) ProtoMessage() {}

func (x *HostControlRequest_Hello) ProtoReflect() protoreflect.Message {
	mi := &file_terminal_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostControlRequest_Hello.ProtoReflect.Descriptor instead.
func (*HostControlRequest_Hello) Descriptor() ([]byte, []int) {
	return file_terminal_proto_rawDescGZIP(), []int{2, 0}
}

func (x *HostControlRequest_Hello) GetTrustedSecret() string {
	if x != nil {
		return x.TrustedSecret
	}
	return ""
}

type HostControlResponse_Hello struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A unique identifier that the HostService assigns to this Host
	Locator string `protobuf:"bytes,1,opt,name=locator,proto3" json:"locator,omitempty"`
}

func (x *HostControlResponse_Hello) Reset() {
	*x = HostControlResponse_Hello{}
	if protoimpl.UnsafeEnabled {
		mi := &file_terminal_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostControlResponse_Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostControlResponse_Hello) ProtoMessage() {}

func (x *HostControlResponse_Hello) ProtoReflect() protoreflect.Message {
	mi := &file_terminal_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostControlResponse_Hello.ProtoReflect.Descriptor instead.
func (*HostControlResponse_Hello) Descriptor() ([]byte, []int) {
	return file_terminal_proto_rawDescGZIP(), []int{3, 0}
}

func (x *HostControlResponse_Hello) GetLocator() string {
	if x != nil {
		return x.Locator
	}
	return ""
}

type HostControlResponse_DataChannelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Token that can be used to create a new data channel
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// Dimensions of the new terminal that will be created and attached to the data channel
	RequestedDimensions *TerminalDimensions `protobuf:"bytes,3,opt,name=requested_dimensions,json=requestedDimensions,proto3" json:"requested_dimensions,omitempty"`
}

func (x *HostControlResponse_DataChannelRequest) Reset() {
	*x = HostControlResponse_DataChannelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_terminal_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostControlResponse_DataChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostControlResponse_DataChannelRequest) ProtoMessage() {}

func (x *HostControlResponse_DataChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_terminal_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostControlResponse_DataChannelRequest.ProtoReflect.Descriptor instead.
func (*HostControlResponse_DataChannelRequest) Descriptor() ([]byte, []int) {
	return file_terminal_proto_rawDescGZIP(), []int{3, 1}
}

func (x *HostControlResponse_DataChannelRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *HostControlResponse_DataChannelRequest) GetRequestedDimensions() *TerminalDimensions {
	if x != nil {
		return x.RequestedDimensions
	}
	return nil
}

type HostDataRequest_Hello struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Host's locator
	Locator string `protobuf:"bytes,1,opt,name=locator,proto3" json:"locator,omitempty"`
	// Token provided to the Host in DataChannelRequest
	Token string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *HostDataRequest_Hello) Reset() {
	*x = HostDataRequest_Hello{}
	if protoimpl.UnsafeEnabled {
		mi := &file_terminal_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostDataRequest_Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostDataRequest_Hello) ProtoMessage() {}

func (x *HostDataRequest_Hello) ProtoReflect() protoreflect.Message {
	mi := &file_terminal_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostDataRequest_Hello.ProtoReflect.Descriptor instead.
func (*HostDataRequest_Hello) Descriptor() ([]byte, []int) {
	return file_terminal_proto_rawDescGZIP(), []int{4, 0}
}

func (x *HostDataRequest_Hello) GetLocator() string {
	if x != nil {
		return x.Locator
	}
	return ""
}

func (x *HostDataRequest_Hello) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_terminal_proto protoreflect.FileDescriptor

var file_terminal_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xbf, 0x02, 0x0a, 0x14, 0x47, 0x75, 0x65, 0x73, 0x74, 0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e,
	0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x33, 0x0a, 0x05, 0x68, 0x65, 0x6c,
	0x6c, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x47, 0x75, 0x65, 0x73, 0x74,
	0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e,
	0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x48, 0x00, 0x52, 0x05, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x42,
	0x0a, 0x11, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x64, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x54, 0x65, 0x72, 0x6d,
	0x69, 0x6e, 0x61, 0x6c, 0x44, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x48, 0x00,
	0x52, 0x10, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x44, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f,
	0x6e, 0x73, 0x12, 0x1d, 0x0a, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x05, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x05, 0x69, 0x6e, 0x70, 0x75,
	0x74, 0x1a, 0x81, 0x01, 0x0a, 0x05, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x6c,
	0x6f, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x6f,
	0x63, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x46, 0x0a,
	0x14, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x5f, 0x64, 0x69, 0x6d, 0x65, 0x6e,
	0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x54, 0x65,
	0x72, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x44, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73,
	0x52, 0x13, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x44, 0x69, 0x6d, 0x65, 0x6e,
	0x73, 0x69, 0x6f, 0x6e, 0x73, 0x42, 0x0b, 0x0a, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0x45, 0x0a, 0x15, 0x47, 0x75, 0x65, 0x73, 0x74, 0x54, 0x65, 0x72, 0x6d, 0x69,
	0x6e, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x06, 0x6f,
	0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x44, 0x61,
	0x74, 0x61, 0x48, 0x00, 0x52, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x42, 0x0b, 0x0a, 0x09,
	0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x84, 0x01, 0x0a, 0x12, 0x48, 0x6f,
	0x73, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x31, 0x0a, 0x05, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x48, 0x00, 0x52, 0x05, 0x68, 0x65,
	0x6c, 0x6c, 0x6f, 0x1a, 0x2e, 0x0a, 0x05, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x25, 0x0a, 0x0e,
	0x74, 0x72, 0x75, 0x73, 0x74, 0x65, 0x64, 0x5f, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x74, 0x72, 0x75, 0x73, 0x74, 0x65, 0x64, 0x53, 0x65, 0x63,
	0x72, 0x65, 0x74, 0x42, 0x0b, 0x0a, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0xca, 0x02, 0x0a, 0x13, 0x48, 0x6f, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x05, 0x68, 0x65, 0x6c, 0x6c,
	0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x43, 0x6f,
	0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x48, 0x65,
	0x6c, 0x6c, 0x6f, 0x48, 0x00, 0x52, 0x05, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x5b, 0x0a, 0x14,
	0x64, 0x61, 0x74, 0x61, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x48, 0x6f, 0x73,
	0x74, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2e, 0x44, 0x61, 0x74, 0x61, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x12, 0x64, 0x61, 0x74, 0x61, 0x43, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x0a, 0x05, 0x48, 0x65, 0x6c,
	0x6c, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x1a, 0x72, 0x0a, 0x12,
	0x44, 0x61, 0x74, 0x61, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x46, 0x0a, 0x14, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x65, 0x64, 0x5f, 0x64, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61,
	0x6c, 0x44, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x13, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x44, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73,
	0x42, 0x0b, 0x0a, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xa8, 0x01,
	0x0a, 0x0f, 0x48, 0x6f, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x2e, 0x0a, 0x05, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x48, 0x00, 0x52, 0x05, 0x68, 0x65, 0x6c, 0x6c,
	0x6f, 0x12, 0x1f, 0x0a, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x05, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x06, 0x6f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x1a, 0x37, 0x0a, 0x05, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x6c,
	0x6f, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x6f,
	0x63, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x42, 0x0b, 0x0a, 0x09, 0x6f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x82, 0x01, 0x0a, 0x10, 0x48, 0x6f, 0x73,
	0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a,
	0x11, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x64, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x54, 0x65, 0x72, 0x6d, 0x69,
	0x6e, 0x61, 0x6c, 0x44, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x48, 0x00, 0x52,
	0x10, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x44, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e,
	0x73, 0x12, 0x1d, 0x0a, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x05, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74,
	0x42, 0x0b, 0x0a, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x5a, 0x0a,
	0x12, 0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x44, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69,
	0x6f, 0x6e, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x77, 0x69, 0x64, 0x74, 0x68, 0x5f, 0x63, 0x6f, 0x6c,
	0x75, 0x6d, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x77, 0x69, 0x64, 0x74,
	0x68, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x68, 0x65, 0x69, 0x67,
	0x68, 0x74, 0x5f, 0x72, 0x6f, 0x77, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x68,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x52, 0x6f, 0x77, 0x73, 0x22, 0x1a, 0x0a, 0x04, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x21, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x54, 0x0a, 0x0c, 0x47, 0x75, 0x65, 0x73,
	0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x44, 0x0a, 0x0f, 0x54, 0x65, 0x72, 0x6d,
	0x69, 0x6e, 0x61, 0x6c, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x15, 0x2e, 0x47, 0x75,
	0x65, 0x73, 0x74, 0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x16, 0x2e, 0x47, 0x75, 0x65, 0x73, 0x74, 0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e,
	0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x30, 0x01, 0x32, 0x86,
	0x01, 0x0a, 0x0b, 0x48, 0x6f, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3f,
	0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x12, 0x13, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x74,
	0x72, 0x6f, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x30, 0x01, 0x12,
	0x36, 0x0a, 0x0b, 0x44, 0x61, 0x74, 0x61, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x10,
	0x2e, 0x48, 0x6f, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x11, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x28, 0x01, 0x30, 0x01, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x69, 0x72, 0x72, 0x75, 0x73, 0x6c, 0x61, 0x62, 0x73,
	0x2f, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_terminal_proto_rawDescOnce sync.Once
	file_terminal_proto_rawDescData = file_terminal_proto_rawDesc
)

func file_terminal_proto_rawDescGZIP() []byte {
	file_terminal_proto_rawDescOnce.Do(func() {
		file_terminal_proto_rawDescData = protoimpl.X.CompressGZIP(file_terminal_proto_rawDescData)
	})
	return file_terminal_proto_rawDescData
}

var file_terminal_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_terminal_proto_goTypes = []interface{}{
	(*GuestTerminalRequest)(nil),                   // 0: GuestTerminalRequest
	(*GuestTerminalResponse)(nil),                  // 1: GuestTerminalResponse
	(*HostControlRequest)(nil),                     // 2: HostControlRequest
	(*HostControlResponse)(nil),                    // 3: HostControlResponse
	(*HostDataRequest)(nil),                        // 4: HostDataRequest
	(*HostDataResponse)(nil),                       // 5: HostDataResponse
	(*TerminalDimensions)(nil),                     // 6: TerminalDimensions
	(*Data)(nil),                                   // 7: Data
	(*Error)(nil),                                  // 8: Error
	(*GuestTerminalRequest_Hello)(nil),             // 9: GuestTerminalRequest.Hello
	(*HostControlRequest_Hello)(nil),               // 10: HostControlRequest.Hello
	(*HostControlResponse_Hello)(nil),              // 11: HostControlResponse.Hello
	(*HostControlResponse_DataChannelRequest)(nil), // 12: HostControlResponse.DataChannelRequest
	(*HostDataRequest_Hello)(nil),                  // 13: HostDataRequest.Hello
}
var file_terminal_proto_depIdxs = []int32{
	9,  // 0: GuestTerminalRequest.hello:type_name -> GuestTerminalRequest.Hello
	6,  // 1: GuestTerminalRequest.change_dimensions:type_name -> TerminalDimensions
	7,  // 2: GuestTerminalRequest.input:type_name -> Data
	7,  // 3: GuestTerminalResponse.output:type_name -> Data
	10, // 4: HostControlRequest.hello:type_name -> HostControlRequest.Hello
	11, // 5: HostControlResponse.hello:type_name -> HostControlResponse.Hello
	12, // 6: HostControlResponse.data_channel_request:type_name -> HostControlResponse.DataChannelRequest
	13, // 7: HostDataRequest.hello:type_name -> HostDataRequest.Hello
	7,  // 8: HostDataRequest.output:type_name -> Data
	6,  // 9: HostDataResponse.change_dimensions:type_name -> TerminalDimensions
	7,  // 10: HostDataResponse.input:type_name -> Data
	6,  // 11: GuestTerminalRequest.Hello.requested_dimensions:type_name -> TerminalDimensions
	6,  // 12: HostControlResponse.DataChannelRequest.requested_dimensions:type_name -> TerminalDimensions
	0,  // 13: GuestService.TerminalChannel:input_type -> GuestTerminalRequest
	2,  // 14: HostService.ControlChannel:input_type -> HostControlRequest
	4,  // 15: HostService.DataChannel:input_type -> HostDataRequest
	1,  // 16: GuestService.TerminalChannel:output_type -> GuestTerminalResponse
	3,  // 17: HostService.ControlChannel:output_type -> HostControlResponse
	5,  // 18: HostService.DataChannel:output_type -> HostDataResponse
	16, // [16:19] is the sub-list for method output_type
	13, // [13:16] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_terminal_proto_init() }
func file_terminal_proto_init() {
	if File_terminal_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_terminal_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuestTerminalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_terminal_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuestTerminalResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_terminal_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostControlRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_terminal_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostControlResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_terminal_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_terminal_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_terminal_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TerminalDimensions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_terminal_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_terminal_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_terminal_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuestTerminalRequest_Hello); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_terminal_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostControlRequest_Hello); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_terminal_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostControlResponse_Hello); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_terminal_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostControlResponse_DataChannelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_terminal_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostDataRequest_Hello); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_terminal_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*GuestTerminalRequest_Hello_)(nil),
		(*GuestTerminalRequest_ChangeDimensions)(nil),
		(*GuestTerminalRequest_Input)(nil),
	}
	file_terminal_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*GuestTerminalResponse_Output)(nil),
	}
	file_terminal_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*HostControlRequest_Hello_)(nil),
	}
	file_terminal_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*HostControlResponse_Hello_)(nil),
		(*HostControlResponse_DataChannelRequest_)(nil),
	}
	file_terminal_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*HostDataRequest_Hello_)(nil),
		(*HostDataRequest_Output)(nil),
	}
	file_terminal_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*HostDataResponse_ChangeDimensions)(nil),
		(*HostDataResponse_Input)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_terminal_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_terminal_proto_goTypes,
		DependencyIndexes: file_terminal_proto_depIdxs,
		MessageInfos:      file_terminal_proto_msgTypes,
	}.Build()
	File_terminal_proto = out.File
	file_terminal_proto_rawDesc = nil
	file_terminal_proto_goTypes = nil
	file_terminal_proto_depIdxs = nil
}
