package command

import (
	"github.com/cirruslabs/terminal/pkg/host"
	"github.com/google/uuid"
	"github.com/spf13/cobra"
)

var hostServerAddress string
var hostTrustedSecret string

func runHost(cmd *cobra.Command, args []string) error {
	logger, err := getLogger()
	if err != nil {
		return err
	}
	defer func() {
		_ = logger.Sync()
	}()

	if hostTrustedSecret == "" {
		hostTrustedSecret = uuid.New().String()
		logger.Sugar().Infof("genereated trusted secret: %s", hostTrustedSecret)
	}

	terminalHost, err := host.New(
		host.WithLogger(logger),
		host.WithServerAddress(hostServerAddress),
		host.WithTrustedSecret(hostTrustedSecret),
		host.WithLocatorCallback(func(locator string) error {
			logger.Sugar().Infof("received locator: %s", locator)
			return nil
		}),
	)
	if err != nil {
		return err
	}

	return terminalHost.Run(cmd.Context())
}

func newHostCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "host [flags]",
		Short: "Run terminal host on a local machine, useful for debugging",
		RunE:  runHost,
	}

	cmd.PersistentFlags().BoolVar(&debug, "debug", false, "enable debugging")

	cmd.PersistentFlags().StringVar(&hostServerAddress, "server-address", "https://terminal.cirrus-ci.com:443",
		"terminal server address")
	cmd.PersistentFlags().StringVar(&hostTrustedSecret, "trusted-secret", "",
		"trusted secret, a secure one is auto-generated by default")

	return cmd
}
